
#version 430

layout (local_size_x = 256) in;

#define PI_FLOAT 3.1415927410125732421875f
layout (std430, binding = 0) buffer PositionBuffer {
    vec4 positions[]; // position xyz, density in w
};

layout (std430, binding = 1) buffer VelocityBuffer {
    vec4 velocities[]; // velocity xyz, density out w
};

layout (std430, binding = 2) buffer AccelerationBuffer {
    vec4 accelerations[]; // acceleration xyz, dummy w
};

layout (std430, binding = 3) buffer GridBuffer {
    int grid[];
};

layout (std430, binding = 4) buffer GridCountBuffer {
    int gridCount[];
};

uniform vec3 grid_size;
uniform ivec3 grid_resolution;
uniform vec3 grid_min_boundary; // Min boundary of the grid in world space
uniform uint particle_max_count_cell;

uniform float u_particle_radius;
uniform float u_particle_mass = 1.0f;
uniform float smoothing_length = 1.0f;

//uniform float u_bulk = 1000f;
uniform float u_viscosity = 3000.0f;
uniform float u_density_0 = 1000.0f;
uniform float u_gravity = 9.8f;



// Gradient of the spiky kernel
float SpikyKernel(float r, float h) {
    if (r >= 0.0 && r <= h) {
        float hr = (h - r);
        return 15.0 / (3.14159265359 * pow(h, 6.0)) * hr * hr * hr;
    } else {
        return 0.0;
    }
}

float ViscosityKernel(float r, float h) {
    if (r >= 0.0 && r <= h) {
        float r3h3 = - (r * r * r) / (2.0 * (h * h * h));
        float r2h2 = (r * r) / (h * h);
        float r1h1 = h / (2.0 * r);
        return 15.0 / (3.14159265359 * pow(h, 3.0)) * (r3h3 + r2h2 + r1h1 - 1);
    } else {
        return 0.0;
    }
}

// https://arxiv.org/pdf/1706.10263 page 7/26
float KernelFunction(float r, float h)
{
    float s = r / h;
    float section_data = 0.0;

    if ( s >= 0.0 && s < 1.0) 
    {
		section_data =  s * s * s - 6 * s + 6;
	} 
    else if (s >= 1.0 && s < 2.0) {
		section_data =  pow((2-s), 3.0);
	}
    else
        section_data = 0.0;

    return section_data / (3.0 * 3.14159265359 * pow(h, 2.0));
}

void main() {
    uint id = gl_GlobalInvocationID.x;
        if(id >= positions.length()) {
		return;
	}
    vec3 pos = positions[id].xyz;

    vec3 cell_size = grid_size / vec3(grid_resolution);

    ivec3 cell_index = ivec3(floor((pos - grid_min_boundary) / cell_size));

     const float h = smoothing_length;

    const float viscosity = u_viscosity;
    const float mass = u_particle_mass;

    // Compute Density was done in another compute shader
    vec3 force = vec3(0.0, 0.0, 0.0); // gravity

    const vec3 gravity = vec3(0.0, u_gravity, 0.0);

    // Loop over neighboring cells


    vec3 pressure_force = vec3(0.0, 0.0, 0.0);
    vec3 viscosity_force = vec3(0.0, 0.0, 0.0);


    // Loop over neighboring cells

    for (int z = -1; z <= 1; ++z) {
        for (int y = -1; y <= 1; ++y) {
            for (int x = -1; x <= 1; ++x) {

                ivec3 neighborCellIndex = cell_index + ivec3(x, y, z);
                if (neighborCellIndex.x < 0 || neighborCellIndex.y < 0 || neighborCellIndex.z < 0 ||
                    neighborCellIndex.x >= grid_resolution.x || neighborCellIndex.y >= grid_resolution.y || neighborCellIndex.z >= grid_resolution.z) {
                    continue;
                }

                int flatIndex = neighborCellIndex.x + neighborCellIndex.y * int(grid_resolution.x) + neighborCellIndex.z * int(grid_resolution.x * grid_resolution.y);
//                int neighborCount = gridCount[flatIndex];
                int neighborCount = min(gridCount[flatIndex], int(particle_max_count_cell));

                for (int i = 0; i < neighborCount; ++i) {
                    int neighborIndex = grid[flatIndex * particle_max_count_cell + i];
                    if (neighborIndex == int(id)) continue;

                    vec3 neighborPos = positions[neighborIndex].xyz;

                    vec3 delta = pos - neighborPos;
                    float r = length(delta);
                    if(r == 0.0)
				        continue;
			        if (r < h) {
                        pressure_force -= mass * (velocities[id].w + velocities[neighborIndex].w) / (2.0f * positions[neighborIndex].w) *
                        // gradient of spiky kernel
                            -45.f / (PI_FLOAT * pow(h, 6.0)) * pow(h - r, 2.0) * normalize(delta);

                        viscosity_force += mass * (velocities[neighborIndex].xyz - velocities[id].xyz) / positions[neighborIndex].w *  
                    // Laplacian of viscosity kernel
                        45.f / (PI_FLOAT * pow(h, 6.0)) * (h - r);
                    }
                }
            }
        }
    }

//    const float rhoi = velocities[id].w;
//    for (uint i = 0; i < positions.length(); ++i) {
//        if (i != id) {
//            vec3 neighborPos = positions[i].xyz;
//            vec3 d = pos - neighborPos;
//
//            float d_length = length(d);
////            float r2 = max(dot(d, d), 0.00000001); // r * r
//
//            if(d_length < h)
//            {
//                const float rhoj = velocities[i].w; // Get density of neighbor
//                float q = d_length / h;
//                float u = 1.0 - q;
//                float w0 = C0 * u / rhoi / rhoj;
//                float wp = w0 * Cp * (rhoi + rhoj - 2 * density_0) * u / q;
//                float wv = w0 * Cv;
//                vec3 dv = velocities[id].xyz - velocities[i].xyz;
////
//                force += wv * dv + wp * d;
//
//            }
//        }
//    }

    viscosity_force *= viscosity;

    vec3 external_force =  -positions[id].w * gravity;

    //force = pressure_force  + external_force;
    force = pressure_force + viscosity_force + external_force;
    accelerations[id].xyz =  force / positions[id].w;
}
