stages:
  - build
  # - deploy

build-job:
  stage: build
  # tags:
  #  - DOCS
  before_script:
    # - apt install texlive-full doxygen graphviz git python3 -y
    - cd RSEngine/doxy_scripts
    - chmod +x gen_doc.sh
  script:
    - ./gen_doc.sh
  artifacts:
    untracked: false
    when: on_success
    access: all
    expire_in: 30 days
    paths:
      - "RSEngine/refman.pdf"
