"""
0. 임포트 및 전역변수
1. 복사 할 파일들 지정
2. 저장 할 파일 경로
3. 저장 할 파일 2개 지정 (merged_shader.h, merged_shader.cpp)
4. def function 헤더에 따라 저장할 const char* shader_name 설정
5. 헤더 > 코멘트 헤더
6. 헤더 > shader_name 복사
7. CPP > 코멘트 헤더
8. CPP > shader 내용 복사

"""

import io
import pathlib
from collections.abc import Mapping
from datetime import datetime
from typing import Sequence, List, Dict

ROOT: pathlib.Path = pathlib.Path(__file__).parent
SHADER_EXT = {
    ".vert", ".frag", ".comp"
}

SUFFIX_MAP = {
    ".vert": "vs",
    ".frag": "fs",
    ".comp": "cs",
}

OUTPUT_FILE_NAME = "RSMergedShaders"
INCLUDE_GUARD_NAME = "RS_MERGED_SHADER_H_"


HEADER_TEMPLATE = r"""
/******************************************************************************
 * \file   {file_name}.h
 * \brief  This file contains all of glsl shader code.
 * The shader codes are vertex, fragment and compute shader.
 * This file auto generated by python script.
 * DO NOT EDIT THIS FILE DIRECTLY.
 * 
 * 
 * \author Jinseob Park
 * \date   {current_date}
 *****************************************************************************/
#ifndef {guard_name}
#define {guard_name}

{content}

#endif // !{guard_name}
""".lstrip()


SOURCE_TEMPLATE = r"""
#include "pch.h"
#include "{file_name}.h"

{content}

""".lstrip()


SHADER_GROUP_TEMPLATE = r"""
/{sep_line}/

{contents}

"""

SHADER_TEMPLATE = r"""
const char* {shader_name} = R"(

{shader_content}

)";
"""


SHADER_FILES: Sequence[pathlib.Path] = [
    subdir
    for subdir
    in (ROOT / "resources/GLSL").iterdir()
    if subdir.suffix in SHADER_EXT
]

# Output header and source files
HEADER_FILE = ROOT / f"src/Resource/Pipeline/{OUTPUT_FILE_NAME}.h"
SOURCE_FILE = ROOT / f"src/Resource/Pipeline/{OUTPUT_FILE_NAME}.cpp"

DATE_FORMAT = "%Y/%m/%d"


def get_converted_file_name(file_path : pathlib.Path) -> str:
    """
    Convert shader filename to `{filename}_{suffix_code}` for use in C++.

    Args:
        file_path: file to convert

    Returns:
        converted `{filename}_{suffix_code}` string

    """
    return f"{file_path.stem}_{SUFFIX_MAP[file_path.suffix]}"


def generate_header_file():
    """
    Generate header file
    """

    current_date = datetime.now().strftime(DATE_FORMAT)
    content_list : list = []
    for shader_file in SHADER_FILES:
        content_list.append(f"extern const char* {get_converted_file_name(shader_file)};")
        #content.join(f"extern const char* {get_converted_file_name(shader_file)};\n\n")

    content = '\n\n'.join(content_list)
    HEADER_FILE.write_text(
        HEADER_TEMPLATE.format(
            file_name = OUTPUT_FILE_NAME,
            current_date = current_date,
            guard_name = INCLUDE_GUARD_NAME,
            content = content
        ),
        'utf-8'
    )


def generate_source_file():
    shader_group_paths: Dict[str, List[pathlib.Path]] = {}

    # identify group of shaders in 1st pass
    for shader_file in SHADER_FILES:
        key = "_".join(get_converted_file_name(shader_file).split("_")[:-1])

        #print(f"Found {shader_file}")

        # fetch shader list, if key's absent set it with new empty list and return it
        shader_arr = shader_group_paths.setdefault(key, [])
        shader_arr.append(shader_file)

    # for each group generate content
    contents = []

    for shader_group_name, paths in shader_group_paths.items():
        #print(f"Generating shader group '{shader_group_name}' with {paths}")
        shader_texts = [
            SHADER_TEMPLATE.format(
                shader_content=path.read_text("utf-8"),
                shader_name=get_converted_file_name(path),
            )
            for path in paths
        ]

        contents.append(
            SHADER_GROUP_TEMPLATE.format(
                sep_line=f"{' ' + shader_group_name + ' ':*^78}",
                contents="\n\n".join(shader_texts),
            )
        )

    # write to file
    SOURCE_FILE.write_text(
        SOURCE_TEMPLATE.format(
            file_name=OUTPUT_FILE_NAME,
            content="\n\n".join(contents)
        )
    )


if __name__ == '__main__':

    generate_header_file()
    generate_source_file()

    print(f"Header and source files generated: {HEADER_FILE}, {SOURCE_FILE}")

