/******************************************************************************
 * \file   RSMergedShaders.h
 * \brief  This file contains all of glsl shader code.
 * The shader codes are vertex, fragment and compute shader.
 * This file auto generated by python script.
 * DO NOT EDIT THIS FILE DIRECTLY.
 * 
 * 
 * \author Jinseob Park
 * \date   2025/11/16
 *****************************************************************************/
#ifndef RS_MERGED_SHADER_H_
#define RS_MERGED_SHADER_H_

extern const char* ComputeCMUDensity_cs;

extern const char* ComputeCMUForce_cs;

extern const char* ComputeCMUPost_cs;

extern const char* ComputeGridAcc_cs;

extern const char* ComputeGridBatch_cs;

extern const char* ComputeGridDensity_cs;

extern const char* ComputeGridInit_cs;

extern const char* ComputeGridPost_cs;

extern const char* ComputeGridSPH_cs;

extern const char* ComputeParticles_cs;

extern const char* ComputeParticlesSPH_cs;

extern const char* ComputeParticleTriBuffer_cs;

extern const char* ComputeSPH_pressure_cs;

extern const char* ComputeTrace_cs;

extern const char* default_fs;

extern const char* default_vs;

extern const char* DefaultMVP_fs;

extern const char* DefaultMVP_vs;

extern const char* DefaultMVPL_fs;

extern const char* DefaultMVPL_vs;

extern const char* DefaultMVPLT_fs;

extern const char* DefaultMVPLT_vs;

extern const char* DefaultMVPLT_Opaque_fs;

extern const char* DefaultMVPLT_Opaque_vs;

extern const char* DefaultParticle_fs;

extern const char* DefaultParticle_vs;

extern const char* DeferredComposite_fs;

extern const char* DeferredQuad_vs;

extern const char* DeferredScreenSpaceReflection_fs;

extern const char* DeferredScreenSpaceReflectionBlur_fs;

extern const char* DeferredSSAO_fs;

extern const char* DeferredSSAOBlur_fs;

extern const char* Depth_fs;

extern const char* Depth_vs;

extern const char* DMaterialPbr_fs;

extern const char* DMaterialPbr_vs;

extern const char* DParticleRender_fs;

extern const char* DParticleRender_vs;

extern const char* DPointClipper_fs;

extern const char* DPointClipper_vs;

extern const char* DPointMultiFloatVtk_fs;

extern const char* DPointMultiFloatVtk_vs;

extern const char* DPointSingleFloatVtk_fs;

extern const char* DPointSingleFloatVtk_vs;

extern const char* DPointSingleUintVtk_fs;

extern const char* DPointSingleUintVtk_vs;

extern const char* DynamicComputeDensity_cs;

extern const char* DynamicComputeForce_cs;

extern const char* DynamicComputePost_cs;

extern const char* DynamicInOutFlowBatch_cs;

extern const char* DynamicInOutFlowCreator_cs;

extern const char* HUDPicking_fs;

extern const char* HUDPicking_vs;

extern const char* HudText_fs;

extern const char* HudText_vs;

extern const char* HudTexture_fs;

extern const char* HudTexture_vs;

extern const char* MaterialPbr_fs;

extern const char* MaterialPbr_vs;

extern const char* MaterialPbr_gbuffer_fs;

extern const char* MaterialPbr_gbuffer_vs;

extern const char* ParticleDefaultShader_fs;

extern const char* ParticleDefaultShader_vs;

extern const char* ParticleDefaultShader_backup_fs;

extern const char* PointCloudShader_fs;

extern const char* PointCloudShader_vs;

extern const char* PointMultiFloatVtk_fs;

extern const char* PointMultiFloatVtk_vs;

extern const char* PointSingleFloatVtk_fs;

extern const char* PointSingleFloatVtk_vs;

extern const char* PointSingleUintVtk_fs;

extern const char* PointSingleUintVtk_vs;

extern const char* PointVtkRender_fs;

extern const char* PointVtkRender_vs;

extern const char* Point_gbuffer_fs;

extern const char* Point_gbuffer_vs;

extern const char* QuadTexture_fs;

extern const char* QuadTexture_vs;

extern const char* QuadTextureR32_fs;

extern const char* QuadTextureR32_vs;

extern const char* Quad_Debug_fs;

extern const char* Quad_Debug_vs;

extern const char* ShadowMapping_fs;

extern const char* ShadowMapping_vs;

extern const char* Skybox_fs;

extern const char* Skybox_vs;

extern const char* SolidColor_fs;

extern const char* SolidColor_vs;

#endif // !RS_MERGED_SHADER_H_
