#version 460
layout(local_size_x = 256) in; // Work group size

layout (std430, binding = 3) buffer GridBuffer {
    int grid[];
};

layout (std430, binding = 4) buffer GridCountBuffer {
    int gridCount[];
};

void main() {
    uint id = gl_GlobalInvocationID.x;

    // Initlize grid and gridCount
        if(id < grid.length()) {
    	grid[id] = -1;
	}

        if(id < gridCount.length()) {
	    gridCount[id] = 0;
    }
}