#version 460

layout (local_size_x = 256) in;

#define PI_FLOAT 3.1415927410125732421875f
layout (std430, binding = 0) buffer PositionBuffer {
    vec4 positions[]; // position xyz, density w
};

layout (std430, binding = 1) buffer VelocityBuffer {
    vec4 velocities[]; // velocity xyz, pressure w
};

layout (std430, binding = 3) buffer GridBuffer {
    int grid[];
};

layout (std430, binding = 4) buffer GridCountBuffer {
    int gridCount[];
};

uniform vec3 grid_size;
uniform ivec3 grid_resolution;
uniform vec3 grid_min_boundary; // Min boundary of the grid in world space
uniform uint particle_max_count_cell;

uniform float particle_radius;
uniform float smoothing_length = 1.0f;
uniform float particle_mass = 1.0f;
uniform float u_density_0 = 1000.0f;
uniform float u_gas_constant = 2000.0f; // Gas constant for equation of state

// SPH kernel
float Poly6Kernel(float r, float h) {
    if (r >= 0.0 && r <= h) {
        float hr = (h * h - r * r);
        return 315.0 / (64.0 * 3.14159265359 * pow(h, 9.0)) * hr * hr * hr;
    } else {
        return 0.0;
    }
}

//// Gradient of the spiky kernel
//float SpikyKernel(float r, float h) {
//    if (r >= 0.0 && r <= h) {
//        float hr = (h - r);
//        return 15.0 / (3.14159265359 * pow(h, 6.0)) * hr * hr * hr;
//    } else {
//        return 0.0;
//    }
//}

// https://arxiv.org/pdf/1706.10263 page 7/26
float KernelFunction(float r, float h)
{
    float s = r / h;
    float section_data = 0.0;

    if ( s >= 0.0 && s < 1.0) 
    {
		section_data =  s * s * s - 6 * s + 6;
	} 
    else if (s >= 1.0 && s < 2.0) {
		section_data =  pow((2-s), 3.0);
	}
    else
        section_data = 0.0;

    return section_data / (3.0 * 3.14159265359 * pow(h, 2.0));
}


float ViscosityKernel(float r, float h) {
    if (r >= 0.0 && r <= h) {
        float r3h3 = - (r * r * r) / (2.0 * (h * h * h));
        float r2h2 = (r * r) / (h * h);
        float r1h1 = h / (2.0 * r);
        return 15.0 / (3.14159265359 * pow(h, 3.0)) * (r3h3 + r2h2 + r1h1 - 1);
    } else {
        return 0.0;
    }
}

void main() {
    uint id = gl_GlobalInvocationID.x;
        if(id >= positions.length()) {
		return;
	}
    vec3 pos = positions[id].xyz;

    
    vec3 cell_size = grid_size / vec3(grid_resolution);

    ivec3 cell_index = ivec3(floor((pos - grid_min_boundary) / cell_size));

//    int flat_index = cell_index.x + cell_index.y * grid_resolution.x + cell_index.z * (grid_resolution.x * grid_resolution.y);


//    const float M_PI = 3.1415926535897932384626433832795;

//    // Init settings
//    float h = particle_radius;
//    float h2 = h * h;
//    float h8 = (h2 * h2) * (h2 * h2);
//    float C = 4 * particle_mass / (M_PI * h8);
    
    float density_sum = 0.f;


    // Init settings
    float h = smoothing_length;

    // add self density
	density_sum += particle_mass * /* poly6 kernel */ 315.f * pow( h * h, 3) / (64.f * PI_FLOAT * pow(h, 9));

    // Loop over neighboring cells
//    float density = u_density_0;
    for (int z = -1; z <= 1; ++z) {
        for (int y = -1; y <= 1; ++y) {
            for (int x = -1; x <= 1; ++x) {

                ivec3 neighborCellIndex = cell_index + ivec3(x, y, z);
                if (neighborCellIndex.x < 0 || neighborCellIndex.y < 0 || neighborCellIndex.z < 0 ||
                    neighborCellIndex.x >= grid_resolution.x || neighborCellIndex.y >= grid_resolution.y || neighborCellIndex.z >= grid_resolution.z) {
                    continue;
                }

                int flatIndex = neighborCellIndex.x + neighborCellIndex.y * grid_resolution.x + neighborCellIndex.z *(grid_resolution.x * grid_resolution.y);
                int neighborCount = min(gridCount[flatIndex], int(particle_max_count_cell));

                for (int i = 0; i < neighborCount; ++i) {
                    int neighborIndex = grid[flatIndex * particle_max_count_cell + i];
                    if (neighborIndex == int(id)) continue;

                    vec3 neighborPos = positions[neighborIndex].xyz;
                    vec3 delta = positions[id].xyz - neighborPos;
                    float r = distance(positions[id].xyz, neighborPos);

			        if (r < h) {
			            density_sum += particle_mass * /* poly6 kernel */ 315.f * pow(h * h - r * r, 3) / (64.f * PI_FLOAT * pow(h, 9));
                    }
                }
            }
        }
    }


    density_sum = min(density_sum, 5000.f);
    float pressure = max(u_gas_constant * (density_sum - u_density_0), 0.f);


    positions[id].w = density_sum;
    velocities[id].w = pressure;
}
