#version 460

layout (local_size_x = 256) in;

#define PI_FLOAT 3.1415927410125732421875f
layout (std430, binding = 0) buffer PositionBuffer {
    vec4 positions[]; // position xyz, density w
};

layout (std430, binding = 1) buffer VelocityBuffer {
    vec4 velocities[]; // velocity xyz, pressure w
};

layout (std430, binding = 2) buffer AccelerationBuffer {
    vec4 accelerations[]; // acceleration xyz, dummy w
};

uniform float u_particle_radius;
uniform float u_particle_mass = 1.0f;
uniform float smoothing_length = 1.0f;

//uniform float u_bulk = 1000f;
uniform float u_viscosity = 3000.0f;
uniform float u_density_0 = 1000.0f;
uniform float u_gravity = 9.8f;

// Gradient of the spiky kernel
float SpikyKernel(float r, float h) {
    if (r >= 0.0 && r <= h) {
        float hr = (h - r);
        return 15.0 / (3.14159265359 * pow(h, 6.0)) * hr * hr * hr;
    } else {
        return 0.0;
    }
}

float ViscosityKernel(float r, float h) {
    if (r >= 0.0 && r <= h) {
        float r3h3 = - (r * r * r) / (2.0 * (h * h * h));
        float r2h2 = (r * r) / (h * h);
        float r1h1 = h / (2.0 * r);
        return 15.0 / (3.14159265359 * pow(h, 3.0)) * (r3h3 + r2h2 + r1h1 - 1);
    } else {
        return 0.0;
    }
}

// https://arxiv.org/pdf/1706.10263 page 7/26
float KernelFunction(float r, float h)
{
    float s = r / h;
    float section_data = 0.0;

    if ( s >= 0.0 && s < 1.0) 
    {
		section_data =  s * s * s - 6 * s + 6;
	} 
    else if (s >= 1.0 && s < 2.0) {
		section_data =  pow((2-s), 3.0);
	}
    else
        section_data = 0.0;

    return section_data / (3.0 * 3.14159265359 * pow(h, 2.0));
}

void main() {
    uint id = gl_GlobalInvocationID.x;

    vec3 pos = positions[id].xyz;
//    accelerations[id].xyz = vec3(0.0, 0.0, 0.0);
    const float h = smoothing_length;

    const float viscosity = u_viscosity;
    const float mass = u_particle_mass;

    // Compute Density was done in another compute shader
    vec3 force = vec3(0.0, 0.0, 0.0); // gravity

    const vec3 gravity = vec3(0.0, u_gravity, 0.0);

    // Loop over neighboring cells


    vec3 pressure_force = vec3(0.0, 0.0, 0.0);
    vec3 viscosity_force = vec3(0.0, 0.0, 0.0);

    //  calculate pressure force
    for (uint i = 0; i < positions.length(); ++i) {
        if (i != id) 
        {
            vec3 delta = pos - positions[i].xyz;
            float r = length(delta);
            if(r == 0.0)
				continue;
			if (r < h) {
                pressure_force -= mass * (velocities[id].w + velocities[i].w) / (2.0f * positions[i].w) *
                // gradient of spiky kernel
                    -45.f / (PI_FLOAT * pow(h, 6.0)) * pow(h - r, 2.0) * normalize(delta);

                viscosity_force += mass * (velocities[i].xyz - velocities[id].xyz) / positions[i].w *  
            // Laplacian of viscosity kernel
                45.f / (PI_FLOAT * pow(h, 6.0)) * (h - r);
            }
        }
    }
    viscosity_force *= viscosity;

    vec3 external_force =  -positions[id].w * gravity;

    //force = pressure_force  + external_force;
    force = pressure_force + viscosity_force + external_force;
    accelerations[id].xyz =  force / positions[id].w;
}
